col_names <- names(admissions)
admissions[,col_names] <- lapply(admissions[,col_names] , factor)
library(arules)
library(arulesViz)
rules <- apriori(admissions,  parameter = list(minlen=2, supp=0.005, conf=0.6), appearance = list(rhs=c("admit=1"), default="lhs"))
quality(rules) <- round(quality(rules), digits=3)
rules.sorted <- sort(rules, by="lift")
inspect(rules.sorted)
plot(rules)
